// Tradução de nomes de seleções/clubes para português do Brasil.
// Fonte: nomes retornados pela The Odds API (em inglês).
// Para times não mapeados, retornamos o nome original.

const TEAMS_PT: Record<string, string> = {
  // Seleções — Copa do Mundo
  "Argentina": "Argentina",
  "Australia": "Austrália",
  "Austria": "Áustria",
  "Belgium": "Bélgica",
  "Bolivia": "Bolívia",
  "Brazil": "Brasil",
  "Cameroon": "Camarões",
  "Canada": "Canadá",
  "Chile": "Chile",
  "Colombia": "Colômbia",
  "Costa Rica": "Costa Rica",
  "Croatia": "Croácia",
  "Czech Republic": "República Tcheca",
  "Czechia": "República Tcheca",
  "Denmark": "Dinamarca",
  "Ecuador": "Equador",
  "Egypt": "Egito",
  "England": "Inglaterra",
  "Finland": "Finlândia",
  "France": "França",
  "Germany": "Alemanha",
  "Ghana": "Gana",
  "Greece": "Grécia",
  "Hungary": "Hungria",
  "Iceland": "Islândia",
  "Iran": "Irã",
  "Ireland": "Irlanda",
  "Italy": "Itália",
  "Ivory Coast": "Costa do Marfim",
  "Japan": "Japão",
  "Mexico": "México",
  "Morocco": "Marrocos",
  "Netherlands": "Holanda",
  "New Zealand": "Nova Zelândia",
  "Nigeria": "Nigéria",
  "North Macedonia": "Macedônia do Norte",
  "Northern Ireland": "Irlanda do Norte",
  "Norway": "Noruega",
  "Panama": "Panamá",
  "Paraguay": "Paraguai",
  "Peru": "Peru",
  "Poland": "Polônia",
  "Portugal": "Portugal",
  "Qatar": "Catar",
  "Romania": "Romênia",
  "Russia": "Rússia",
  "Saudi Arabia": "Arábia Saudita",
  "Scotland": "Escócia",
  "Senegal": "Senegal",
  "Serbia": "Sérvia",
  "Slovakia": "Eslováquia",
  "Slovenia": "Eslovênia",
  "South Africa": "África do Sul",
  "South Korea": "Coreia do Sul",
  "Spain": "Espanha",
  "Sweden": "Suécia",
  "Switzerland": "Suíça",
  "Tunisia": "Tunísia",
  "Turkey": "Turquia",
  "Ukraine": "Ucrânia",
  "United States": "Estados Unidos",
  "USA": "Estados Unidos",
  "Uruguay": "Uruguai",
  "Wales": "País de Gales",

  // Clubes — alguns nomes comuns que mudam em PT
  "Bayern Munich": "Bayern de Munique",
  "Manchester United": "Manchester United",
  "Manchester City": "Manchester City",
  "Atletico Madrid": "Atlético de Madrid",
  "Real Madrid": "Real Madrid",
  "Inter Milan": "Internazionale",
  "AC Milan": "Milan",
};

export function ptTeam(name: string): string {
  return TEAMS_PT[name] ?? name;
}
