/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as JogoResponsavelRouteImport } from './routes/jogo-responsavel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthEntrarRouteImport } from './routes/auth.entrar'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'
import { Route as ApiAdminSyncRouteImport } from './routes/api/admin/sync'
import { Route as AuthenticatedJogosIdRouteImport } from './routes/_authenticated/jogos.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoResponsavelRoute = JogoResponsavelRouteImport.update({
  id: '/jogo-responsavel',
  path: '/jogo-responsavel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEntrarRoute = AuthEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSyncRoute = ApiAdminSyncRouteImport.update({
  id: '/api/admin/sync',
  path: '/api/admin/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJogosIdRoute = AuthenticatedJogosIdRouteImport.update({
  id: '/jogos/$id',
  path: '/jogos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/jogo-responsavel': typeof JogoResponsavelRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/entrar': typeof AuthEntrarRoute
  '/jogos/$id': typeof AuthenticatedJogosIdRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/jogo-responsavel': typeof JogoResponsavelRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/entrar': typeof AuthEntrarRoute
  '/jogos/$id': typeof AuthenticatedJogosIdRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/jogo-responsavel': typeof JogoResponsavelRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/entrar': typeof AuthEntrarRoute
  '/_authenticated/jogos/$id': typeof AuthenticatedJogosIdRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jogo-responsavel'
    | '/metodologia'
    | '/privacidade'
    | '/termos'
    | '/dashboard'
    | '/diario'
    | '/perfil'
    | '/auth/cadastro'
    | '/auth/entrar'
    | '/jogos/$id'
    | '/api/admin/sync'
    | '/api/public/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jogo-responsavel'
    | '/metodologia'
    | '/privacidade'
    | '/termos'
    | '/dashboard'
    | '/diario'
    | '/perfil'
    | '/auth/cadastro'
    | '/auth/entrar'
    | '/jogos/$id'
    | '/api/admin/sync'
    | '/api/public/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/jogo-responsavel'
    | '/metodologia'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/dashboard'
    | '/_authenticated/diario'
    | '/_authenticated/perfil'
    | '/auth/cadastro'
    | '/auth/entrar'
    | '/_authenticated/jogos/$id'
    | '/api/admin/sync'
    | '/api/public/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  JogoResponsavelRoute: typeof JogoResponsavelRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiAdminSyncRoute: typeof ApiAdminSyncRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo-responsavel': {
      id: '/jogo-responsavel'
      path: '/jogo-responsavel'
      fullPath: '/jogo-responsavel'
      preLoaderRoute: typeof JogoResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/entrar': {
      id: '/auth/entrar'
      path: '/entrar'
      fullPath: '/auth/entrar'
      preLoaderRoute: typeof AuthEntrarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sync': {
      id: '/api/admin/sync'
      path: '/api/admin/sync'
      fullPath: '/api/admin/sync'
      preLoaderRoute: typeof ApiAdminSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jogos/$id': {
      id: '/_authenticated/jogos/$id'
      path: '/jogos/$id'
      fullPath: '/jogos/$id'
      preLoaderRoute: typeof AuthenticatedJogosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedJogosIdRoute: typeof AuthenticatedJogosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedJogosIdRoute: AuthenticatedJogosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthEntrarRoute: typeof AuthEntrarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCadastroRoute: AuthCadastroRoute,
  AuthEntrarRoute: AuthEntrarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  JogoResponsavelRoute: JogoResponsavelRoute,
  MetodologiaRoute: MetodologiaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiAdminSyncRoute: ApiAdminSyncRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
